__include__: [
  '../deim_dfine/dfine_hgnetv2_s_coco.yml',
  '/public/home/linhanran2023/FE-DETR-main/configs/dataset/visdrone_detection.yml',
  # '/public/home/linhanran2023/FE-DETR-main/configs/dataset/LEVIR-Ship_detection.yml',
  # '/public/home/linhanran2023/FE-DETR-main/configs/dataset/tinyperson_detection.yml',
  # '/public/home/linhanran2023/FE-DETR-main/configs/dataset/UAVDT_detection.yml',
  # '/public/home/linhanran2023/FE-DETR-main/configs/dataset/UAVDT2024_detection.yml',
  '../runtime.yml',
  '../base/dataloader_dfine.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
  '../base/deim.yml'
]

print_freq: 20
output_dir: ./outputs/deim_hgnetv2_s_custom

DEIM:
  encoder: HybridEncoder_QEPOLA
  backbone: HGNetv2_FGPC

HGNetv2_FGPC:
  name: 'B1'
  agg: 'WTLSK'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  pretrained: False

HybridEncoder_QEPOLA:
  in_channels: [256, 512, 1024]
  feat_strides: [8, 16, 32]
  use_encoder_idx: [1] 
  dim_feedforward: 512

  # cross
  expansion: 0.34
  depth_mult: 0.5

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*bn).*$'
      lr: 0.0002
    - 
      params: '^(?=.*(?:norm|bn)).*$'     # except bias
      weight_decay: 0.

  lr: 0.0004
  betas: [0.9, 0.999]
  weight_decay: 0.0001


# Increase to search for the optimal ema
epoches: 132 

## Our LR-Scheduler
flat_epoch: 64    
no_aug_epoch: 12


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 64, 120]   # list 

  collate_fn:
    mixup_epochs: [4, 64]
    stop_epoch: 120
  total_batch_size: 4
val_dataloader:
  total_batch_size: 4